### ISSUE TITLE
pull requests

### ISSUE THREAD

**Issue by aldudko** [simenon/LostTreasure#21]
Hi,

I made a couple of changes in my local version of the addon such as:

- removed dependency on LibStub
- replaced Libs/LibMapPins-1.0, Libs/LibAddonMenu-2.0, Libs/CustomCompassPins with external dependencies and removed Libs/*

Would you be interested in accepting pull requests?

**Comment by simenon** [comment]
Yeah, just go ahead. I need to update it anyways, and your changes are welcome.
