### ISSUE TITLE
markarth update reverted pin updates

### ISSUE THREAD

**Issue by tiker** [simenon/LostTreasure#51]
The commit merging Markarth update reverted some updates I submitted earlier to fix some pin updates a couple months ago.

**Comment by Scootworks** [comment]
hi @tiker 
well, the live version was behind the dev version. I didn‘t check the closed requests and merged the dev into master branch, I‘m sorry. Could you make a new one, please?

**Comment by tiker** [comment]
I'll make a new pull request.  No worries.  I have a few additions as well.
